# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: 
title: Mindee Rosen
email: <a href="mailto:mindee@lacanna.net">mindee@lacanna.net</a>
author: Zack LaCanna
description: >  
  Coaching women to infinite possibilites with spiritual health, prosperity, and wealth changes! 
  
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/mindee.rosen
  - title: calender
    url: https://linkedin.com/in/zacklacanna
  - title: email
    url: mailto:mindee@lacanna.net
  - title: instagram
    url: https://www.instagram.com/mindeerosen
